function derivative = dPadTF(p,x)
% input: a specific TF value
% output: derivative of TR at this particular TF

Kab= p(1);
Kba = p(2);
Kbd = p(3);
Kdb0 = p(4);
Kcd = p(5);
Kdc = p(6);
Kca0 = p(7);
% Kac = p(8); % neq
Kac = p(1)*p(3)*p(6)*p(7)/(p(5)*p(4)*p(2)); % eq


derivative = ((-1).*Kab+(-1).*Kac).^(-1).*(Kab.^3.*Kac.*Kba.*Kca0.^2.*Kcd.^2.* ...
  Kdb0.^3.*Kdc.*x.^5.*(Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd+Kab.*Kca0.*Kdc+Kba.* ...
  Kca0.*Kdc+Kbd.*Kca0.*Kdc+8.*Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^7).*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.* ...
  Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.* ...
  Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^8).^(-2)+(-5).*Kab.^3.*Kac.*Kba.*Kca0.^2.*Kcd.^2.* ...
  Kdb0.^3.*Kdc.*x.^4.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.* ...
  Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.* ...
  Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^8).^(-1)+Kab.^(-2).*Kac.^(-1).*Kca0.^(-1).*Kdb0.^(-3).* ...
  x.^(-4).*(Kab.^4.*Kac.*Kbd.*Kca0.^2.*Kcd.^2.*Kdb0.^3.*Kdc.*x.^5.*(Kab.* ...
  Kac.*Kba.*Kbd.*Kca0.*Kcd+Kab.*Kca0.*Kdc+Kba.*Kca0.*Kdc+Kbd.*Kca0.*Kdc+ ...
  8.*Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^7).*(Kab.* ...
  Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.* ...
  Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+ ...
  Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-2)+ ...
  Kab.^3.*Kac.^2.*Kbd.*Kca0.^2.*Kcd.^2.*Kdb0.^3.*Kdc.*x.^5.*(Kab.*Kac.* ...
  Kba.*Kbd.*Kca0.*Kcd+Kab.*Kca0.*Kdc+Kba.*Kca0.*Kdc+Kbd.*Kca0.*Kdc+8.* ...
  Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^7).*(Kab.* ...
  Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.* ...
  Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+ ...
  Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-2)+ ...
  Kab.^4.*Kac.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.*x.^6.*(Kab.*Kac.*Kba.*Kbd.* ...
  Kca0.*Kcd+Kab.*Kca0.*Kdc+Kba.*Kca0.*Kdc+Kbd.*Kca0.*Kdc+8.*Kab.^2.* ...
  Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^7).*(Kab.*Kbd.*Kcd+ ...
  Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.* ...
  Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.* ...
  Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-2)+Kab.^3.* ...
  Kac.^2.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.*x.^6.*(Kab.*Kac.*Kba.*Kbd.*Kca0.* ...
  Kcd+Kab.*Kca0.*Kdc+Kba.*Kca0.*Kdc+Kbd.*Kca0.*Kdc+8.*Kab.^2.*Kac.^3.* ...
  Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^7).*(Kab.*Kbd.*Kcd+Kac.*Kbd.* ...
  Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.* ...
  Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.* ...
  Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-2)+Kab.^3.*Kac.*Kba.* ...
  Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.*x.^6.*(Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd+ ...
  Kab.*Kca0.*Kdc+Kba.*Kca0.*Kdc+Kbd.*Kca0.*Kdc+8.*Kab.^2.*Kac.^3.*Kba.^4.* ...
  Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^7).*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.* ...
  Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.* ...
  x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.* ...
  Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-2)+Kab.^4.*Kac.^3.*Kba.*Kca0.^2.*Kcd.^2.* ...
  Kdb0.^5.*Kdc.*x.^7.*(Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd+Kab.*Kca0.*Kdc+Kba.* ...
  Kca0.*Kdc+Kbd.*Kca0.*Kdc+8.*Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^7).*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.* ...
  Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.* ...
  Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^8).^(-2)+(-5).*Kab.^4.*Kac.*Kbd.*Kca0.^2.*Kcd.^2.* ...
  Kdb0.^3.*Kdc.*x.^4.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.* ...
  Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.* ...
  Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^8).^(-1)+(-5).*Kab.^3.*Kac.^2.*Kbd.*Kca0.^2.*Kcd.^2.* ...
  Kdb0.^3.*Kdc.*x.^4.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.* ...
  Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.* ...
  Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.* ...
  Kdb0.^6.*Kdc.*x.^8).^(-1)+(-6).*Kab.^4.*Kac.*Kca0.^2.*Kcd.^2.*Kdb0.^4.* ...
  Kdc.*x.^5.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+ ...
  Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+ ...
  Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.* ...
  Kdc.*x.^8).^(-1)+(-6).*Kab.^3.*Kac.^2.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.* ...
  x.^5.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.* ...
  Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.* ...
  Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.* ...
  x.^8).^(-1)+(-6).*Kab.^3.*Kac.*Kba.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.* ...
  x.^5.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.* ...
  Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.* ...
  Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.* ...
  x.^8).^(-1)+(-7).*Kab.^4.*Kac.^3.*Kba.*Kca0.^2.*Kcd.^2.*Kdb0.^5.*Kdc.* ...
  x.^6.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.* ...
  Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.* ...
  Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.* ...
  x.^8).^(-1))+(-4).*Kab.^(-2).*Kac.^(-1).*Kca0.^(-1).*Kdb0.^(-3).*x.^(-5) ...
  .*((-1).*Kab.^4.*Kac.*Kbd.*Kca0.^2.*Kcd.^2.*Kdb0.^3.*Kdc.*x.^5.*(Kab.* ...
  Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.* ...
  Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+ ...
  Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-1)+(-1) ...
  .*Kab.^3.*Kac.^2.*Kbd.*Kca0.^2.*Kcd.^2.*Kdb0.^3.*Kdc.*x.^5.*(Kab.*Kbd.* ...
  Kcd+Kac.*Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.* ...
  Kcd.*x+Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.* ...
  Kac.^3.*Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-1)+(-1).* ...
  Kab.^4.*Kac.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.*x.^6.*(Kab.*Kbd.*Kcd+Kac.* ...
  Kbd.*Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+ ...
  Kab.*Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.* ...
  Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-1)+(-1).*Kab.^3.* ...
  Kac.^2.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.*x.^6.*(Kab.*Kbd.*Kcd+Kac.*Kbd.* ...
  Kcd+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.* ...
  Kca0.*Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.* ...
  Kba.^4.*Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-1)+(-1).*Kab.^3.*Kac.* ...
  Kba.*Kca0.^2.*Kcd.^2.*Kdb0.^4.*Kdc.*x.^6.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+ ...
  Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.* ...
  Kdc.*x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.* ...
  Kca0.^2.*Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-1)+(-1).*Kab.^4.*Kac.^3.*Kba.* ...
  Kca0.^2.*Kcd.^2.*Kdb0.^5.*Kdc.*x.^7.*(Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kab.* ...
  Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kac.*Kba.*Kbd.*Kca0.*Kcd.*x+Kab.*Kca0.*Kdc.* ...
  x+Kba.*Kca0.*Kdc.*x+Kbd.*Kca0.*Kdc.*x+Kab.^2.*Kac.^3.*Kba.^4.*Kca0.^2.* ...
  Kcd.^3.*Kdb0.^6.*Kdc.*x.^8).^(-1)));
