function Pa = Pa_ss4(p,TF)
% input: parameters and TF value
% output: steady state solution for Pa

Kab= p(1);
Kba = p(2);
Kbd = p(3);
Kdb0 = p(4);
Kcd = p(5);
Kdc = p(6);
Kca0 = p(7);
% Kac = p(8); % neq
Kac = p(1)*p(3)*p(6)*p(7)/(p(5)*p(4)*p(2)); % eq

% probability of state a at steady state for 4 state system
Kca = Kca0*TF;
Kdb = Kdb0*TF;

Pa = ((-1).*Kab+(-1).*Kac).^(-1).*((-1).*Kba.*(Kab.*Kca.*Kdb+Kab.*Kcd.*Kdb+ ...
  Kac.*Kcd.*Kdb+Kab.*Kca.*Kdc).*(Kab.*Kbd.*Kca+Kac.*Kba.*Kcd+Kab.*Kbd.* ...
  Kcd+Kac.*Kbd.*Kcd+Kac.*Kba.*Kdb+Kab.*Kca.*Kdb+Kba.*Kca.*Kdb+Kab.*Kcd.* ...
  Kdb+Kac.*Kcd.*Kdb+Kba.*Kcd.*Kdb+Kac.*Kba.*Kdc+Kab.*Kbd.*Kdc+Kac.*Kbd.* ...
  Kdc+Kab.*Kca.*Kdc+Kba.*Kca.*Kdc+Kbd.*Kca.*Kdc).^(-1)+(-1).*Kca.*((-1).* ...
  Kab.*Kca+Kab.*Kdb+Kac.*Kdb+Kca.*Kdb).^(-1).*(Kab.*Kdb+Kac.*Kdb+(-1).* ...
  Kac.*Kba.*(Kab.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kab.*Kca.*Kdc).*( ...
  Kab.*Kbd.*Kca+Kac.*Kba.*Kcd+Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kac.*Kba.*Kdb+ ...
  Kab.*Kca.*Kdb+Kba.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kba.*Kcd.*Kdb+ ...
  Kac.*Kba.*Kdc+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kca.*Kdc+Kba.*Kca.*Kdc+ ...
  Kbd.*Kca.*Kdc).^(-1)+(-1).*Kab.*Kbd.*(Kab.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.* ...
  Kcd.*Kdb+Kab.*Kca.*Kdc).*(Kab.*Kbd.*Kca+Kac.*Kba.*Kcd+Kab.*Kbd.*Kcd+ ...
  Kac.*Kbd.*Kcd+Kac.*Kba.*Kdb+Kab.*Kca.*Kdb+Kba.*Kca.*Kdb+Kab.*Kcd.*Kdb+ ...
  Kac.*Kcd.*Kdb+Kba.*Kcd.*Kdb+Kac.*Kba.*Kdc+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+ ...
  Kab.*Kca.*Kdc+Kba.*Kca.*Kdc+Kbd.*Kca.*Kdc).^(-1)+(-1).*Kac.*Kbd.*(Kab.* ...
  Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kab.*Kca.*Kdc).*(Kab.*Kbd.*Kca+ ...
  Kac.*Kba.*Kcd+Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kac.*Kba.*Kdb+Kab.*Kca.*Kdb+ ...
  Kba.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kba.*Kcd.*Kdb+Kac.*Kba.*Kdc+ ...
  Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kca.*Kdc+Kba.*Kca.*Kdc+Kbd.*Kca.*Kdc) ...
  .^(-1)+(-1).*Kab.*Kdb.*(Kab.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kab.* ...
  Kca.*Kdc).*(Kab.*Kbd.*Kca+Kac.*Kba.*Kcd+Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+ ...
  Kac.*Kba.*Kdb+Kab.*Kca.*Kdb+Kba.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+ ...
  Kba.*Kcd.*Kdb+Kac.*Kba.*Kdc+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kca.*Kdc+ ...
  Kba.*Kca.*Kdc+Kbd.*Kca.*Kdc).^(-1)+(-1).*Kac.*Kdb.*(Kab.*Kca.*Kdb+Kab.* ...
  Kcd.*Kdb+Kac.*Kcd.*Kdb+Kab.*Kca.*Kdc).*(Kab.*Kbd.*Kca+Kac.*Kba.*Kcd+ ...
  Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kac.*Kba.*Kdb+Kab.*Kca.*Kdb+Kba.*Kca.*Kdb+ ...
  Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kba.*Kcd.*Kdb+Kac.*Kba.*Kdc+Kab.*Kbd.*Kdc+ ...
  Kac.*Kbd.*Kdc+Kab.*Kca.*Kdc+Kba.*Kca.*Kdc+Kbd.*Kca.*Kdc).^(-1)+(-1).* ...
  Kba.*Kdb.*(Kab.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kab.*Kca.*Kdc).*( ...
  Kab.*Kbd.*Kca+Kac.*Kba.*Kcd+Kab.*Kbd.*Kcd+Kac.*Kbd.*Kcd+Kac.*Kba.*Kdb+ ...
  Kab.*Kca.*Kdb+Kba.*Kca.*Kdb+Kab.*Kcd.*Kdb+Kac.*Kcd.*Kdb+Kba.*Kcd.*Kdb+ ...
  Kac.*Kba.*Kdc+Kab.*Kbd.*Kdc+Kac.*Kbd.*Kdc+Kab.*Kca.*Kdc+Kba.*Kca.*Kdc+ ...
  Kbd.*Kca.*Kdc).^(-1)));
end 
